"use strict";
const seed=[{id:"thomas",title:"Thomas & Lorelei",plots:[{id:"p1",title:"The Soul Hook awakens",notes:"Thomas accidentally steals Lorelei’s cards.",open:true,done:false},{id:"p2",title:"Waiting for the Weaver",notes:"Lorelei must decide whether to trust him.",open:false,done:false},{id:"p3",title:"Escape from the town",notes:"The pair leave together before the Weaver can arrive.",open:false,done:false}]},{id:"cassian",title:"Cassian Grey",plots:[{id:"c1",title:"The cave and the five circles",notes:"Cassian is called to translate the impossible markings.",open:false,done:false}]}];
const $=id=>document.getElementById(id),uid=()=>Math.random().toString(36).slice(2,10);
let books=load("plot-order-books-v1",seed),activeId=localStorage.getItem("plot-order-active-v1")||books[0].id,handleSide=localStorage.getItem("plot-order-handle-v1")||"left",drag=null;
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function active(){return books.find(b=>b.id===activeId)||books[0]}
function save(){localStorage.setItem("plot-order-books-v1",JSON.stringify(books));localStorage.setItem("plot-order-active-v1",activeId);localStorage.setItem("plot-order-handle-v1",handleSide)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){const book=active();$("book-title").textContent=book.title;$("book-list").innerHTML=books.map(b=>`<button class="book-button ${b.id===book.id?"active":""}" data-book="${b.id}"><strong>${esc(b.title)}</strong><small>${b.plots.length} plot ${b.plots.length===1?"point":"points"}</small></button>`).join("");$("book-select").innerHTML=books.map(b=>`<option value="${b.id}" ${b.id===book.id?"selected":""}>${esc(b.title)}</option>`).join("");
 $("handle-left").classList.toggle("selected",handleSide==="left");$("handle-right").classList.toggle("selected",handleSide==="right");const list=$("plot-list");list.className=`plot-list handles-${handleSide}`;
 list.innerHTML=book.plots.length?book.plots.map((p,i)=>`<article class="plot-card ${p.open?"open":""} ${p.done?"done":""} ${drag?.id===p.id?"drag-placeholder":""}" data-id="${p.id}"><button class="drag-handle" aria-label="Drag ${esc(p.title)}">⠿</button><div class="plot-number">${String(i+1).padStart(2,"0")}</div><div class="plot-content"><input class="title-input" value="${esc(p.title)}" aria-label="Plot point title">${p.open?`<textarea aria-label="Notes">${esc(p.notes)}</textarea>`:""}</div><div class="card-actions"><button class="done-button ${p.done?"selected":""}">${p.done?"✓ Done":"Done"}</button><button class="chevron" aria-label="${p.open?"Close":"Open"}">${p.open?"⌃":"⌄"}</button>${p.open?'<button class="delete">Delete</button>':""}</div></article>`).join(""):`<div class="empty"><h2>Your plot starts here</h2><p>Add the first event, scene or turning point.</p><button class="primary" id="first-plot">Add first plot point</button></div>`;save()}
function updatePlot(id,patch){const p=active().plots.find(x=>x.id===id);if(p)Object.assign(p,patch);render()}
$("book-list").onclick=e=>{const b=e.target.closest("[data-book]");if(b){activeId=b.dataset.book;render()}};$("book-select").onchange=e=>{activeId=e.target.value;render()};
$("book-form").onsubmit=e=>{e.preventDefault();const input=$("new-book-title"),title=input.value.trim();if(!title)return;const id=uid();books.push({id,title,plots:[]});activeId=id;input.value="";render()};
$("add-plot").onclick=()=>{active().plots.push({id:uid(),title:"New plot point",notes:"",open:true,done:false});render()};
$("plot-list").onclick=e=>{if(e.target.id==="first-plot"){active().plots.push({id:uid(),title:"Opening scene",notes:"",open:true,done:false});render();return}const card=e.target.closest(".plot-card");if(!card)return;const id=card.dataset.id,p=active().plots.find(x=>x.id===id);if(e.target.closest(".done-button"))updatePlot(id,{done:!p.done});else if(e.target.closest(".chevron"))updatePlot(id,{open:!p.open});else if(e.target.closest(".delete")){active().plots=active().plots.filter(x=>x.id!==id);render()}};
$("plot-list").oninput=e=>{const card=e.target.closest(".plot-card");if(!card)return;const p=active().plots.find(x=>x.id===card.dataset.id);if(e.target.matches(".title-input"))p.title=e.target.value;if(e.target.matches("textarea"))p.notes=e.target.value;save()};
$("open-all").onclick=()=>{active().plots.forEach(p=>p.open=true);render()};$("close-all").onclick=()=>{active().plots.forEach(p=>p.open=false);render()};$("handle-left").onclick=()=>{handleSide="left";render()};$("handle-right").onclick=()=>{handleSide="right";render()};
$("export").onclick=async()=>{const file=new File([JSON.stringify({format:"plot-order-backup",version:1,exportedAt:new Date().toISOString(),books,activeId,handleSide},null,2)],`plot-order-backup-${new Date().toISOString().slice(0,10)}.json`,{type:"application/json"});try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"Plot Order backup",files:[file]})}else{const a=document.createElement("a"),url=URL.createObjectURL(file);a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}message("Backup exported")}catch(e){if(e.name!=="AbortError")message("Backup could not be exported")}};
$("import").onclick=()=>$("import-file").click();$("import-file").onchange=async e=>{const file=e.target.files[0];e.target.value="";if(!file)return;try{const d=JSON.parse(await file.text()),valid=d?.format==="plot-order-backup"&&Array.isArray(d.books)&&d.books.length&&d.books.every(b=>typeof b.id==="string"&&typeof b.title==="string"&&Array.isArray(b.plots));if(!valid)throw 0;if(!confirm("Importing this backup will replace the books currently stored on this device. Continue?"))return;books=d.books;activeId=books.some(b=>b.id===d.activeId)?d.activeId:books[0].id;if(d.handleSide==="left"||d.handleSide==="right")handleSide=d.handleSide;render();message("Backup restored")}catch{message("That is not a valid Plot Order backup")}};
function message(text){$("message").textContent=text;setTimeout(()=>{if($("message").textContent===text)$("message").textContent=""},4000)}
$("plot-list").addEventListener("pointerdown",e=>{const handle=e.target.closest(".drag-handle");if(!handle)return;e.preventDefault();handle.setPointerCapture(e.pointerId);const source=handle.closest(".plot-card"),rect=source.getBoundingClientRect(),ghost=source.cloneNode(true);ghost.classList.add("drag-ghost");ghost.style.cssText+=`;left:${rect.left}px;top:${rect.top}px;width:${rect.width}px;height:${rect.height}px`;document.body.appendChild(ghost);drag={id:source.dataset.id,ghost,offset:e.clientY-rect.top,pointerType:e.pointerType};render();document.addEventListener("touchmove",stopTouch,{passive:false});window.addEventListener("pointermove",move,{passive:false});window.addEventListener("pointerup",end);window.addEventListener("pointercancel",end)});
function stopTouch(e){e.preventDefault()}function move(e){if(!drag)return;e.preventDefault();drag.ghost.style.transform=`translate3d(0,${e.clientY-drag.offset-parseFloat(drag.ghost.style.top)}px,0)`;const cards=[...document.querySelectorAll(".plot-card:not(.drag-placeholder):not(.drag-ghost)")];let to=cards.length;for(let i=0;i<cards.length;i++){const r=cards[i].getBoundingClientRect();if(e.clientY<r.top+r.height/2){to=i;break}}const plots=active().plots,from=plots.findIndex(p=>p.id===drag.id);if(from!==to&&from>=0){const [item]=plots.splice(from,1);plots.splice(to,0,item);render()}}
function end(){if(!drag)return;drag.ghost.remove();drag=null;document.removeEventListener("touchmove",stopTouch);window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end);window.removeEventListener("pointercancel",end);render()}
render();
